# -*- coding: utf-8 -*-
"""
Created on Sun May  9 19:09:46 2021

@author: Benes
"""
mikeQ = ["decisions have consequences",
         "poop",
         "beep boop",
         "oh hi mark",
         "you've been blinded, fool",
         "please follow my blog",
         "dont laugh at my german efficiency",
         "they better not nerf blitzcrank",
         "they better not nerf pyke",
         "hi i am mike and i play blitzcrank",
         "i love donkey kong",
         "i love blitzcrank",
         "imagine playing support",
         "hi, im mike and im german. this is my only personality trait",
         "hi, im mike and im an ENFP. this is my only personality trait",
         "unga bunga _ENFP noises_",
         "ooga booga _ENFP noisees_",
         "ooga booga",
         "oopsie doopsie i made a fucky wucky",
         "i only play killjoy in valorant because she's german",
         "???????",
         "yeehaw",
         "_sad italian noises_",
         "ay bada bing!",
         "bada bing! stromboli! mamma mia!",
         "buca di beppo",
         "leave the gun take the cannoli, bada bing",
         "_monkey noises_",
         "remember when we went B??",
         "oh hell no",
         "https://www.youtube.com/watch?v=uH0hikcwjIA",
         "im mike, im not a bot",
         "math is pretty cool",
         "teemo is the best champion in league of legends",
         "that was not very cash money of you",
         "that's a money move right there",
         ":eyes: what's up gamers",
         "jugeullae?", 
         "we must dance to shame dog planet",
         "dude i feel that",
         "this reminds me of when i was in popreka, ucsc's finest kpop dance group",
         "cki is pain", 
         "your honor, that's cap", 
         "im a macro player",
         "schnucki", 
         "please look at this german content \nhttps://www.youtube.com/watch?v=39UDZMgPg5k",
         "taric mains are psychopaths"]

mike8ball = ["oh heck yeah",
             "oh hell no",
             "yis",
             "no lmao",
             ":0 sure",
             ":eyes: maybe",
             "yes swear on me mum",
             "nO",
             "oui oui",
             "NOPE",
             "i mean i guess so",
             "no that sounds spooky",
             "??? i don't know",
             "yes as long as there's no xerath involved",
             "unfortunately no, gamer", 
             "i mean okay yeah",
             "no your honor",
             "im gonna go with a yes your honor",
             "yes but only with teemo",
             "yes, bada bing",
             "yeenaw (no)",
             "lmao",
             "yikes",
             "yes i believe",
             "no :'0"]
